#!/bin/bash

sub=$1
inDir=$2
ses=$3
streamline=$4
sift=$5
threads=$6
direction=$7
topupFlag=$8
upsampleFlag=$9
voxelSize=${10}
codedir=${11}


source ${codedir}/make_diff_names ${sub} ${inDir} ${ses} ${streamline} ${sift} ${threads} ${direction} ${topupFlag} ${upsampleFlag} ${voxelSize}

cd ${tractDir}

if [ ${upsampleFlag} = yes ]; then
	temp5TTP=${fiveTTP2dwi_warp_up}
else
	temp5TTP=${fiveTTP2dwi_warp}
fi


tckgen ${WMFOD_norm}.mif ${fulltrack}.tck -act ${temp5TTP}.nii.gz -backtrack -crop_at_gmwmi -seed_dynamic ${WMFOD_norm}.mif -angle 22.5 -maxlength 250 -minlength 10 -power 1.0 -select ${streamline} -force -nthreads ${threads}

tcksift -act ${temp5TTP}.nii.gz ${fulltrack}.tck ${WMFOD_norm}.mif ${sifttrack}.tck -term_number ${sift} -force -nthreads ${threads}
