#!/bin/bash
# ./diffusion_metrics 

subName=$1
inDir=$2
ses=$3
streamline=$4
sift=$5
threads=$6
direction=$7
topupFlag=$8
upsampleFlag=$9
voxelSize=${10}
codedir=${11}


source ${codedir}/make_diff_names ${subName} ${inDir} ${ses} ${streamline} ${sift} ${threads} ${direction} ${topupFlag} ${upsampleFlag} ${voxelSize}

sub=${subName}_ses-${ses}

cd ${metricDir}

if [ ${upsampleFlag} = yes ]; then
	tempDiff=${dwi_preproc_BC_up}
	tempMask=${meanb0_bet2_mask_up}
else
	tempDiff=${dwi_preproc_BC}
	tempMask=${meanb0_bet2_mask}
fi


dtifit -k ${tempDiff}.nii.gz -o ${sub}_dtifit -m ${tempMask}.nii.gz -r ${dwi}.bvec -b ${dwi}.bval --save_tensor
fslmaths ${sub}_dtifit_L2.nii.gz -add ${sub}_dtifit_L3.nii.gz -div 2 ${dtifitRD}.nii.gz
fslmaths ${sub}_dtifit_L1.nii.gz ${dtifitAD}.nii.gz


mrconvert ${dtifitFA}.nii.gz ${dtifitFA}.mif -force
mrconvert ${dtifitMD}.nii.gz ${dtifitMD}.mif -force
mrconvert ${dtifitAD}.nii.gz ${dtifitAD}.mif -force
mrconvert ${dtifitRD}.nii.gz ${dtifitRD}.mif -force
