#!/bin/bash

subName=$1
inDir=$2
ses=$3
streamline=$4
sift=$5
threads=$6
direction=$7
topupFlag=$8
upsampleFlag=$9
voxelSize=${10}
codedir=${11}


source ${codedir}/make_diff_names ${subName} ${inDir} ${ses} ${streamline} ${sift} ${threads} ${direction} ${topupFlag} ${upsampleFlag} ${voxelSize}


sub=${subName}_ses-${ses}

if [ ${upsampleFlag} = yes ]; then
	# move UPSAMPLED preprocessed diffusion and mean b0
	cp ${dwi_preproc_BC_up}.nii.gz ${diffDir}/${sub}_preprocessed_dwi.nii.gz
	cp ${meanb0_up}.nii.gz ${diffDir}/${sub}_preprocessed_meanb0.nii.gz
	cp ${meanb0_bet2_up}.nii.gz ${diffDir}/${sub}_preprocessed_meanb0_bet2.nii.gz
	cp ${meanb0_bet2_mask_up}.nii.gz ${diffDir}/${sub}_preprocessed_meanb0_bet2_mask.nii.gz
else
	# move preprocessed diffusion and mean b0
	cp ${dwi_preproc_BC}.nii.gz ${diffDir}/${sub}_preprocessed_dwi.nii.gz
	cp ${meanb0}.nii.gz ${diffDir}/${sub}_preprocessed_meanb0.nii.gz
	cp ${meanb0_bet2}.nii.gz ${diffDir}/${sub}_preprocessed_meanb0_bet2.nii.gz
	cp ${meanb0_bet2_mask}.nii.gz ${diffDir}/${sub}_preprocessed_meanb0_bet2_mask.nii.gz
fi





# move diffusion metrics
cp ${dtifitFA}.nii.gz ${diffDir}/${sub}_FA.nii.gz
cp ${dtifitMD}.nii.gz ${diffDir}/${sub}_MD.nii.gz
cp ${dtifitAD}.nii.gz ${diffDir}/${sub}_AD.nii.gz
cp ${dtifitRD}.nii.gz ${diffDir}/${sub}_RD.nii.gz


# move connectome matrix outputs
cp ${aparcasegCount} ${diffDir}/${sub}_connectome_aparc+aseg_count.csv
cp ${aparcasegLength} ${diffDir}/${sub}_connectome_aparc+aseg_length.csv
cp ${aparcasegFA} ${diffDir}/${sub}_connectome_aparc+aseg_FA.csv
cp ${aparcasegMD} ${diffDir}/${sub}_connectome_aparc+aseg_MD.csv
cp ${aparcasegAD} ${diffDir}/${sub}_connectome_aparc+aseg_AD.csv
cp ${aparcasegRD} ${diffDir}/${sub}_connectome_aparc+aseg_RD.csv

cp ${aparca2009sCount} ${diffDir}/${sub}_connectome_aparca2009s+aseg_count.csv
cp ${aparca2009sLength} ${diffDir}/${sub}_connectome_aparca2009s+aseg_length.csv
cp ${aparca2009sFA} ${diffDir}/${sub}_connectome_aparca2009s+aseg_FA.csv
cp ${aparca2009sMD} ${diffDir}/${sub}_connectome_aparca2009s+aseg_MD.csv
cp ${aparca2009sAD} ${diffDir}/${sub}_connectome_aparca2009s+aseg_AD.csv
cp ${aparca2009sRD} ${diffDir}/${sub}_connectome_aparca2009s+aseg_RD.csv



