#!/bin/bash
###make_fnames
# make_diffusion_names $sub $dir $session $streamlineNo $siftNo $threads $direction $topupFlag $upsampleFlag $voxelSize
#####################################################################
sub=$1
inDir=$2
session=$3
streamline=$4
sift=$5
threads=$6
pedir=$7
topupFlag=$8
upsampleFlag=$9
voxel=${10}
####################################################################

mrtrix_path=/usr/local/mrtrix3/share/mrtrix3/labelconvert

sub_ses=${sub}_ses-${session}

##################################

if [ $pedir = none ] ; then
  direction=""
else
  direction=$pedir
fi

if [ $voxel = none ] ; then
  voxelSize=""
else
  voxelSize=$voxel
fi


################################ DIRECTORIES
anatDir=${inDir}/${sub}/ses-${session}/anat
fmapDir=${inDir}/${sub}/ses-${session}/fmap
diffDir=${inDir}/${sub}/ses-${session}/dwi

preprocDir=${diffDir}/preproc
metricDir=${diffDir}/metrics
regDir=${diffDir}/reg
FODdir=${diffDir}/FOD
tractDir=${diffDir}/tract

################################ PRE-PROCESSING

dwi=${diffDir}/${sub_ses}_dwi
dwi_denoise=${preprocDir}/${sub_ses}_dwi_denoised
dwi_degibbs=${preprocDir}/${sub_ses}_dwi_denoised_degibbs
dwi_preproc=${preprocDir}/${sub_ses}_dwi_preproc
dwi_preproc_BC=${preprocDir}/${sub_ses}_dwi_preproc_biasCorr


meanb0_noBC=${preprocDir}/${sub_ses}_meanb0_noBiasCorr
meanb0_noBC_bet2=${preprocDir}/${sub_ses}_meanb0_noBiasCorr_bet2
meanb0=${preprocDir}/${sub_ses}_meanb0
meanb0_bet2=${preprocDir}/${sub_ses}_meanb0_bet2
meanb0_bet2_mask=${preprocDir}/${sub_ses}_meanb0_bet2_mask

### TOPUP
fow=${fmapDir}/${sub_ses}_acq-2mm_dir-fpe_epi
rev=${fmapDir}/${sub_ses}_acq-2mm_dir-rpe_epi
b0_pair=${fmapDir}/${sub_ses}_acq-2mm_topup_pair


################################ UPSAMPLING
meanb0_bet2_up=${preprocDir}/${sub_ses}_meanb0_bet2_upsampled
meanb0_bet2_mask_up=${preprocDir}/${sub_ses}_meanb0_bet2_mask_upsampled
dwi_preproc_BC_up=${preprocDir}/${sub_ses}_dwi_preproc_biasCorr_upsampled
meanb0_up=${preprocDir}/${sub_ses}_meanb0_upsampled


fiveTTP2dwi_warp_up=${regDir}/${sub_ses}_5TTP_hires2dwi_warped_upsampled
aparcaseg2dwi_warp_up=${regDir}/${sub_ses}_aparcaseg2dwi_warped_upsampled
aparca2009s2dwi_warp_up=${regDir}/${sub_ses}_aparca2009sdwi_warped_upsampled

################################ METRICS
dtifitFA=${metricDir}/${sub_ses}_dtifit_FA
dtifitMD=${metricDir}/${sub_ses}_dtifit_MD
dtifitAD=${metricDir}/${sub_ses}_dtifit_AD
dtifitRD=${metricDir}/${sub_ses}_dtifit_RD

################################ 5TTP
fs_T1=${anatDir}/${sub_ses}_brain
aparcaseg=${anatDir}/${sub_ses}_aparc+aseg
aparca2009s=${anatDir}/${sub_ses}_aparc.a2009s+aseg


hires2dwi=${regDir}/${sub_ses}_hires2dwi
HR2dwi2meanb0=${regDir}/${sub_ses}_hires2dwi2meanb0
HR2dwi2meanb0_warp=${HR2dwi2meanb0}_warped
HR2dwi2meanb0_synWarp=${HR2dwi2meanb0}Warp
HR2dwi2meanb0_synAffine=${HR2dwi2meanb0}Affine

base5tt=${regDir}/${sub_ses}_5TTP
base5tt2dwi=${regDir}/5TTP_temp_hires2dwi
base5tt2dwi_warp=${regDir}/5TTP_temp_hires2dwi_warp
fiveTTP2dwi_warp=${regDir}/${sub_ses}_5TTP_hires2dwi_warped


aparcaseg2dwi=${regDir}/${sub_ses}_aparcaseg2dwi
aparcaseg2dwi_warp=${aparcaseg2dwi}_warped

aparca2009s2dwi=${regDir}/${sub_ses}_aparca2009s2dwi
aparca2009s2dwi_warp=${aparca2009s2dwi}_warped

nodes_aparcaseg=${regDir}/${sub_ses}_nodes_aparcaseg
nodes_aparca2009s=${regDir}/${sub_ses}_nodes_aparca2009s

################################ FOD
wmresponse=${FODdir}/${sub_ses}_response_wm.txt
gmresponse=${FODdir}/${sub_ses}_response_gm.txt
csfresponse=${FODdir}/${sub_ses}_response_csf.txt
voxel_resp=${FODdir}/${sub_ses}_response_voxels.mif

WMFOD=${FODdir}/${sub_ses}_WM_FODs
WMFOD_norm=${FODdir}/${sub_ses}_WM_FODs_norm
csfODF=${FODdir}/${sub_ses}_csf_ODF
csfODF_norm=${FODdir}/${sub_ses}_csf_ODF_norm


################################ TRACTOGRAPHY
fulltrack=${tractDir}/${sub_ses}_track_${streamline}
sifttrack=${tractDir}/${sub_ses}_track_${sift}_SIFT


### MEASURES
sampleFA=${tractDir}/${sub_ses}_${sift}_SIFT_mean_FA.csv
sampleMD=${tractDir}/${sub_ses}_${sift}_SIFT_mean_MD.csv
sampleAD=${tractDir}/${sub_ses}_${sift}_SIFT_mean_AD.csv
sampleRD=${tractDir}/${sub_ses}_${sift}_SIFT_mean_RD.csv


# aparcaseg
aparcasegCount=${tractDir}/${sub_ses}_connectome_aparcaseg_${sift}_SIFT_count.csv
aparcasegLength=${tractDir}/${sub_ses}_connectome_aparcaseg_${sift}_SIFT_length.csv
aparcasegFA=${tractDir}/${sub_ses}_connectome_aparcaseg_${sift}_SIFT_FA.csv
aparcasegMD=${tractDir}/${sub_ses}_connectome_aparcaseg_${sift}_SIFT_MD.csv
aparcasegAD=${tractDir}/${sub_ses}_connectome_aparcaseg_${sift}_SIFT_AD.csv
aparcasegRD=${tractDir}/${sub_ses}_connectome_aparcaseg_${sift}_SIFT_RD.csv


# aparca2009s
aparca2009sCount=${tractDir}/${sub_ses}_connectome_aparca2009s_${sift}_SIFT_count.csv
aparca2009sLength=${tractDir}/${sub_ses}_connectome_aparca2009s_${sift}_SIFT_length.csv
aparca2009sFA=${tractDir}/${sub_ses}_connectome_aparca2009s_${sift}_SIFT_FA.csv
aparca2009sMD=${tractDir}/${sub_ses}_connectome_aparca2009s_${sift}_SIFT_MD.csv
aparca2009sAD=${tractDir}/${sub_ses}_connectome_aparca2009s_${sift}_SIFT_AD.csv
aparca2009sRD=${tractDir}/${sub_ses}_connectome_aparca2009s_${sift}_SIFT_RD.csv


#######################################################################
